### ISSUE TITLE
[Warning timer error]

### ISSUE THREAD

**Issue by Motzumoto** [NexInfinite/DiscordBotHelp#5]
`Traceback (most recent call last):
  File "C:\Users\cuzto\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\cuzto\Desktop\agb local\Cogs\mod.py", line 696, in on_message
    end = datetime.strptime(user["warn_time"], "%m/%d/%Y")
KeyError: 'warn_time'`

**Comment by NexInfinite** [comment]
If you just updated this from the old warning system; the json file has a new layout and so all users will need to be reset, I'm sure there is a way of doing this without resetting the file, but the simplest way is to reset the file.
